name: phone_monitoring

description: A Flutter mobile application for monitoring device metrics.

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.3
  firebase_core: ^1.10.6
  provider: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter