name: phone_monitoring

description: A Flutter mobile application for monitoring device metrics.

dependencies:
  flutter:
    sdk: flutter
  device_info_plus: ^3.4.0
  battery_plus: ^1.4.0
  flutter_cpu_temperature: ^0.0.1
  provider: ^6.0.0
  charts_flutter: ^0.10.0
  sqflite: ^2.1.0
  path: ^1.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter